name: Continuos Integration
on:
  push:
    branches:
      - dev

jobs:
  continuos-integration:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.
      - name: run install, build and test
        run: |
          npm install
          npx cypress run
